import { useCallback, useEffect, useRef, useState } from 'react';
import { toast } from 'react-toastify';
import { useGitHubAuth } from '../../../features/github/hooks/useGitHubAuth';
import { useDeployToGitHub } from '../../../features/github/hooks/useGitHubDeploy';
import { ProjectStorageRepository } from '../../../shared/services/storage/ProjectStorageRepository';
import { buildProjectPayloadForBackend } from '../../../features/export/utils/projectExportUtils';
import type { BesserProject } from '../../../shared/types/project';
import { getPostHog } from '../../../shared/services/analytics/lazy-analytics';

// localStorage helpers for tracking previously deployed repos per project
const DEPLOY_LINKED_REPO_PREFIX = 'besser_deploy_linked_';

function getDeployLinkedRepo(projectId: string): { owner: string; repo: string } | null {
  try {
    const raw = localStorage.getItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}`);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && parsed.owner && parsed.repo) return parsed;
    return null;
  } catch {
    return null;
  }
}

function saveDeployLinkedRepo(projectId: string, owner: string, repo: string): void {
  localStorage.setItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}`, JSON.stringify({ owner, repo }));
}

function clearDeployLinkedRepo(projectId: string): void {
  localStorage.removeItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}`);
}

const sanitizeRepoName = (name: string): string => {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');
};

interface UseDeploymentOptions {
  currentProject: BesserProject | null;
  isDeploymentAvailable: boolean;
}

export function useDeployment({ currentProject, isDeploymentAvailable }: UseDeploymentOptions) {
  const {
    isAuthenticated,
    githubSession,
  } = useGitHubAuth();
  const { deployToGitHub, isDeploying: isDeployingToRender, deploymentResult } = useDeployToGitHub();

  const [isDeployDialogOpen, setIsDeployDialogOpen] = useState(false);
  const [isDeployResultOpen, setIsDeployResultOpen] = useState(false);
  const [githubRepoName, setGithubRepoName] = useState('');
  const [githubRepoDescription, setGithubRepoDescription] = useState('');
  const [githubRepoPrivate, setGithubRepoPrivate] = useState(false);
  const [useExistingRepo, setUseExistingRepo] = useState(false);
  const [linkedRepo, setLinkedRepo] = useState<{ owner: string; repo: string } | null>(null);
  const [commitMessage, setCommitMessage] = useState('');

  // Reset linked repo state when the active project changes
  useEffect(() => {
    if (currentProject) {
      const linked = getDeployLinkedRepo(currentProject.id);
      setLinkedRepo(linked);
      setUseExistingRepo(!!linked);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
    }
  }, [currentProject?.id]);

  const handleOpenDeployDialog = useCallback(() => {
    if (!isDeploymentAvailable) {
      toast.info('Deploy is available for Class and GUI diagrams.');
      return;
    }
    if (!isAuthenticated) {
      toast.info('Connect to GitHub first.');
      return;
    }
    if (!currentProject) {
      toast.error('Create or load a project first.');
      return;
    }

    setCommitMessage('');
    const linked = getDeployLinkedRepo(currentProject.id);
    if (linked) {
      setLinkedRepo(linked);
      setGithubRepoName(linked.repo);
      setUseExistingRepo(true);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
      setGithubRepoName(sanitizeRepoName(currentProject.name) || 'besser-webapp');
    }
    setGithubRepoDescription('Web application generated by BESSER');
    setGithubRepoPrivate(false);
    setIsDeployDialogOpen(true);
  }, [isDeploymentAvailable, isAuthenticated, currentProject]);

  const handleOpenDeployDialogRef = useRef(handleOpenDeployDialog);
  handleOpenDeployDialogRef.current = handleOpenDeployDialog;

  // Listen for assistant-driven deploy event
  useEffect(() => {
    const handleAssistantDeploy = (_e: Event) => {
      handleOpenDeployDialogRef.current();
    };

    window.addEventListener('wme:assistant-deploy-app', handleAssistantDeploy);
    return () => window.removeEventListener('wme:assistant-deploy-app', handleAssistantDeploy);
  }, []);

  const handlePublishToRender = useCallback(async () => {
    if (!currentProject) {
      toast.error('No project available for deployment.');
      return;
    }
    if (!githubSession) {
      toast.error('GitHub session not found. Please reconnect.');
      return;
    }
    if (!githubRepoName.trim()) {
      toast.error('Repository name is required.');
      return;
    }

    const projectForDeploy = ProjectStorageRepository.loadProject(currentProject.id) || currentProject;
    const result = await deployToGitHub(
      buildProjectPayloadForBackend(projectForDeploy),
      sanitizeRepoName(githubRepoName),
      githubRepoDescription.trim() || 'Web application generated by BESSER',
      githubRepoPrivate,
      githubSession,
      useExistingRepo,
      commitMessage,
    );

    if (result?.success) {
      saveDeployLinkedRepo(currentProject.id, result.owner, result.repo_name);
      setIsDeployDialogOpen(false);
      setIsDeployResultOpen(true);

      getPostHog()?.capture('render_deploy_success', {
        deployment_status: 'success',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        repo_url: result.repo_url,
        owner: result.owner,
        files_uploaded: result.files_uploaded,
        is_redeployment: useExistingRepo,
        diagram_type: currentProject.currentDiagramType,
      });
    } else {
      getPostHog()?.capture('render_deploy_failure', {
        deployment_status: 'failed',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        diagram_type: currentProject.currentDiagramType,
      });
    }
  }, [currentProject, githubSession, githubRepoName, githubRepoDescription, githubRepoPrivate, useExistingRepo, commitMessage, deployToGitHub]);

  const handleCreateNewInstead = useCallback(() => {
    if (currentProject?.id) {
      clearDeployLinkedRepo(currentProject.id);
    }
    setLinkedRepo(null);
    setUseExistingRepo(false);
    setGithubRepoName(sanitizeRepoName(currentProject?.name || '') || 'besser-webapp');
  }, [currentProject]);

  return {
    // State
    isDeployDialogOpen,
    isDeployResultOpen,
    githubRepoName,
    githubRepoDescription,
    githubRepoPrivate,
    useExistingRepo,
    linkedRepo,
    commitMessage,
    isDeployingToRender,
    deploymentResult,

    // Setters
    setIsDeployDialogOpen,
    setIsDeployResultOpen,
    setGithubRepoName,
    setGithubRepoDescription,
    setGithubRepoPrivate,
    setCommitMessage,

    // Handlers
    handleOpenDeployDialog,
    handlePublishToRender,
    handleCreateNewInstead,
  };
}
